on:
  push:
    branches: 
      - master
jobs:
  deploy_job:
    name: deploy to stage
    runs-on: [ubuntu-18.04]
    steps:
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: yarn install
      - name: pwd
        run: pwd
      - name: ll
        run: ll
      - name: build
        run: yarn build
