on:
  push:
    branches: 
      - master
jobs:
  deploy_job:
    name: deploy to stage
    runs-on: [ubuntu-18.04]
    steps:
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: yarn install
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: cd ..
        run: cd ..
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: build
        run: yarn build
